---
- hosts: db 
  become: true
  gather_facts: false
  tasks:
     - name: Install packages
       package:
         name: "{{ item }}"
         state: present
       loop:
         - curl
         - finger
         - wget
         - httpd
         - ntp 